[tool.poetry]
name = "mtphandler"
version = "0.2.0"
description = "Tool to work with microtiter plate data."
authors = ["haeussma <83341109+haeussma@users.noreply.github.com>"]
license = "MIT License"
readme = "README.md"
packages = [
    { include = "MTPHandler/core" },
    { include = "MTPHandler/ioutils" },
    { include = "MTPHandler/readers" },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = "1.24.4"
sympy = "^1.12"
sdrdm = {git = "https://github.com/JR-1991/software-driven-rdm.git", branch = "linking-refactor"}
plotly = "^5.18.0"
calipytion = {git = "https://github.com/FAIRChemistry/CaliPytion.git"}
openpyxl = "^3.1.2"

[tool.poetry.group.dev.dependencies]
mkdocs-material = "^9.5.7"
mkautodoc = "^0.2.0"
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
