[tool.poetry]
name = "mtphandler"
version = "0.2.19"
description = "Python package for processing, enriching, and converting microtiter plate data into standardized EnzymeML time-course data, ready for data science."
authors = ["haeussma <83341109+haeussma@users.noreply.github.com>"]
license = "MIT License"
readme = "README.md"
packages = [{ include = "mtphandler" }]
include = ["mtphandler/units/ontomaps.toml"]


[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.4"
plotly = "^5.18.0"
pandas = { version = ">=2.0", extras = ["excel"] }
pyenzyme = { git = "https://github.com/EnzymeML/PyEnzyme.git"}
calipytion = { git = "https://github.com/FAIRChemistry/CaliPytion.git"}
rich = "^13.7.1"
httpx = ">=0.27.2"
loguru = "^0.7.3"
mdmodels = "^0.2.0"

[tool.poetry.group.dev.dependencies]
mkdocs-material = "^9.5.7"
pytest = "^8.0.0"
devtools = "^0.12.2"
ipykernel = "^6.29.4"
mkdocstrings-python = "^1.11.1"
nbval = "^0.11.0"
mkdocs-jupyter = "^0.25.0"
mkdocs-plotly-plugin = "^0.1.3"
notebook = "<7"
jupyter-contrib-nbextensions = "^0.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true
