# Codespell configuration is within .codespellrc
---
name: Codespell

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          path: 'docs'
          exclude_file: docs/overrides/partials/mycontent.html
          ignore_words_list: Varian
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          path: 'specifications'
